Traceback (most recent call last):
  File "/home/cs601-bchang26/anaconda3/envs/ssm_hw5/lib/python3.10/site-packages/requests/compat.py", line 11, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cs601-bchang26/Natural-Language-Processing--Self-Supervised-Models/Assignment 5/main.py", line 1, in <module>
    from data import load_data, create_datasets, create_dataloader, VOCAB_SIZE
  File "/home/cs601-bchang26/Natural-Language-Processing--Self-Supervised-Models/Assignment 5/data.py", line 2, in <module>
    from datasets import load_dataset
  File "/home/cs601-bchang26/anaconda3/envs/ssm_hw5/lib/python3.10/site-packages/datasets/__init__.py", line 18, in <module>
    from .arrow_dataset import Dataset
  File "/home/cs601-bchang26/anaconda3/envs/ssm_hw5/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 62, in <module>
    from huggingface_hub import CommitInfo, CommitOperationAdd, CommitOperationDelete, DatasetCard, DatasetCardData, HfApi
  File "/home/cs601-bchang26/anaconda3/envs/ssm_hw5/lib/python3.10/site-packages/huggingface_hub/__init__.py", line 370, in __getattr__
    submod = importlib.import_module(submod_path)
  File "/home/cs601-bchang26/anaconda3/envs/ssm_hw5/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/cs601-bchang26/anaconda3/envs/ssm_hw5/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 46, in <module>
    import requests
  File "/home/cs601-bchang26/anaconda3/envs/ssm_hw5/lib/python3.10/site-packages/requests/__init__.py", line 45, in <module>
    from .exceptions import RequestsDependencyWarning
  File "/home/cs601-bchang26/anaconda3/envs/ssm_hw5/lib/python3.10/site-packages/requests/exceptions.py", line 9, in <module>
    from .compat import JSONDecodeError as CompatJSONDecodeError
  File "/home/cs601-bchang26/anaconda3/envs/ssm_hw5/lib/python3.10/site-packages/requests/compat.py", line 13, in <module>
    import charset_normalizer as chardet
  File "/home/cs601-bchang26/anaconda3/envs/ssm_hw5/lib/python3.10/site-packages/charset_normalizer/__init__.py", line 23, in <module>
    from charset_normalizer.api import from_fp, from_path, from_bytes, normalize
  File "/home/cs601-bchang26/anaconda3/envs/ssm_hw5/lib/python3.10/site-packages/charset_normalizer/api.py", line 10, in <module>
    from charset_normalizer.md import mess_ratio
  File "charset_normalizer/md.py", line 5, in <module>
ImportError: cannot import name 'COMMON_SAFE_ASCII_CHARACTERS' from 'charset_normalizer.constant' (/home/cs601-bchang26/anaconda3/envs/ssm_hw5/lib/python3.10/site-packages/charset_normalizer/constant.py)
